version: '3.8'

services:
  app:
    image: apple:latest 
    build:
      context: .                  
    ports:
      - "8080:8080"               
    depends_on:
      - redis                     
    networks:
      - app-net

  redis:
    image: redis:7
    ports:
      - "6379:6379"               
    networks:
      - app-net
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"  # RabbitMQ Management UI (Web interface)
      - "5672:5672"    # RabbitMQ AMQP protocol (for connecting clients)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - app-net
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432" 
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
